language: python
python:
- '2.7'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- pip install -r requirements.txt --use-mirrors
script:
- fab clean test jasmine
#deploy:
#  provider: heroku
#  api_key:
#    secure: FYl+nmXR2tSZAV4ue/JBEQdSn8R2sK3IHDlKqMjI4RR5zLKT+sQd3lPiSml2KM/Pb0uvy698hQroAHU3wznjteuKPDYajzBztwunZFXgOKzw1kvL8q8VyvjKfkhh6DTPIKwV+O5NVHq0Ssdd+7dhQM/bLofW/+WbuuXqePaDCCk=
#  run:
#  - python manage.py syncdb --noinput
#  - python manage.py migrate --noinput
#  app:
#    master: yacs-staging
#    production: yacs
